### PR TITLE
fix(Today Birthdays): handle when there is no birthday this day

### LINKED ISSUE #334: Today’s Birthday infinite spinning

### PR DESCRIPTION
**Pull request by renaudjenny**
* Fix #334

### CODE REVIEW

File: ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift [hunk 1]
```diff
@@ -11,16 +11,22 @@ import Backend
...
         viewModel.todayBirthdays.count > 1 ? "Today's Birthdays" : "Today's Birthday"
     }
     
     var body: some View {
         Group {
-            if viewModel.todayBirthdays.isEmpty {
+            if viewModel.isLoading {
                 RowLoadingView()
+            } else if viewModel.todayBirthdays.isEmpty {
+                Text("No Birthday today...")
```
Comment (renaudjenny) [inline ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift:26]: I'm not sure about this one... should `Birthday` takes an `s`? I think so... but it doesn't sound great I let it without... now I'm wondering :D

Comment (Dimillian) [reply ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift:26]: 🤷‍♂️

Comment (renaudjenny) [reply ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift:26]: @ericlewis as a native English speaker, any thoughts?
