### PR TITLE
fix(Category): renames enum Categories to Category and fix typo with …

### LINKED ISSUE #50: Typo for Categories in ItemsViewModel
`var categorie: Categories` should be `var categories: Categories`.

### PR DESCRIPTION
**Pull request by renaudjenny**
…Categorie

* Fix #50

### CODE REVIEW

File: ACHNBrowserUI/ACHNBrowserUI/environements/Items.swift [hunk 1]
```diff
@@ -12,19 +12,21 @@ import Combine
 class Items: ObservableObject {
     static let shared = Items()
     
-    @Published var categories: [Categories: [Item]] = [:]
+    @Published var categories: [Category: [Item]] = [:]
     
-    private var cancellable: [AnyCancellable] = []
+    private var cancellable = Set<AnyCancellable>()
```
Comment (renaudjenny) [inline ACHNBrowserUI/ACHNBrowserUI/environements/Items.swift:17]: I can revert that if you don't like this approach, but it's more conventional to see `cancellables` with `Set<AnyCancellable>`.
Idem for the `.store(in: &cancellable)` instead of `.append(...)` in front of the Publisher.
Tell me if it's OK to go this way.

File: ACHNBrowserUI/ACHNBrowserUI/models/Category.swift [hunk 2]
```diff
@@ -1,5 +1,5 @@
 //
-//  Categories.swift
+//  Category.swift
```
Comment (renaudjenny) [inline ACHNBrowserUI/ACHNBrowserUI/models/Category.swift:2]: I think it should have been named Category right?. and `Categoriesa is when you have an array of categories `let categories: [Category]`

File: ACHNBrowserUI/ACHNBrowserUI/environements/Items.swift (hunk 1 above)
Comment (Dimillian) [reply ACHNBrowserUI/ACHNBrowserUI/environements/Items.swift:17]: It's fine. Ideally we don't want to store them anyway, it's just to keep them referenced so the query to load categories keep running.

File: ACHNBrowserUI/ACHNBrowserUI/models/Category.swift (hunk 2 above)
Comment (Dimillian) [reply ACHNBrowserUI/ACHNBrowserUI/models/Category.swift:2]: Yep

**Comment by Dimillian** [comment]
Very good cleanup and refactor!
